spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/szxyh_db?useSSL=false&characterEncoding=UTF8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Szxyh2Root!
    #password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true